import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        < Header />
        {children}
        < Footer />
      </body>
      <Script src="https://kit.fontawesome.com/b14b4f59b2.js"></Script>
    </html>
  );
}

// # Recommended for most uses
// DATABASE_URL=postgres://neondb_owner:Wyc90YXvInxU@ep-flat-shadow-a5m21t2h-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require

// # For uses requiring a connection without pgbouncer
// DATABASE_URL_UNPOOLED=postgresql://neondb_owner:Wyc90YXvInxU@ep-flat-shadow-a5m21t2h.us-east-2.aws.neon.tech/neondb?sslmode=require

// # Parameters for constructing your own connection string
// PGHOST=ep-flat-shadow-a5m21t2h-pooler.us-east-2.aws.neon.tech
// PGHOST_UNPOOLED=ep-flat-shadow-a5m21t2h.us-east-2.aws.neon.tech
// PGUSER=neondb_owner
// PGDATABASE=neondb
// PGPASSWORD=Wyc90YXvInxU

// # Parameters for Vercel Postgres Templates
// POSTGRES_URL=postgres://neondb_owner:Wyc90YXvInxU@ep-flat-shadow-a5m21t2h-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require
// POSTGRES_URL_NON_POOLING=postgres://neondb_owner:Wyc90YXvInxU@ep-flat-shadow-a5m21t2h.us-east-2.aws.neon.tech/neondb?sslmode=require
// POSTGRES_USER=neondb_owner
// POSTGRES_HOST=ep-flat-shadow-a5m21t2h-pooler.us-east-2.aws.neon.tech
// POSTGRES_PASSWORD=Wyc90YXvInxU
// POSTGRES_DATABASE=neondb
// POSTGRES_URL_NO_SSL=postgres://neondb_owner:Wyc90YXvInxU@ep-flat-shadow-a5m21t2h-pooler.us-east-2.aws.neon.tech/neondb
// POSTGRES_PRISMA_URL=postgres://neondb_owner:Wyc90YXvInxU@ep-flat-shadow-a5m21t2h-pooler.us-east-2.aws.neon.tech/neondb?pgbouncer=true&connect_timeout=15&sslmode=require