import type { Metadata } from "next";
import Script from "next/script";
import {Josefin_Sans, Montserrat } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth";

const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Homepage - Roomiee",
  description: "Generated by create next app",
};

interface Props {
  session: Session | null
}

export default function RootLayout({
  children, session
}: Readonly<Props & {
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefinSans.variable} flex flex-col min-h-screen text-black bg-gray-100 bg-cover font-sans antialiased`}
      >
        <SessionProvider session={session}>
        <main className="flex-grow">{children} </main>
      </SessionProvider>
      </body>
      <Script src="https://kit.fontawesome.com/b14b4f59b2.js"></Script>
    </html>
  );
}