import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'

const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Homepage - Roomiee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body className={`${josefinSans.variable} bg-zinc-900 text-zinc-300`}>
            {children} 
      </body>
    </html>
    </ClerkProvider>
  );
}
