export const rooms = [
  {
    name: "Charming Studio < 10 Miles to Wells' Beaches!",
    price: 168,
    description:
      "A friendly atmosphere and natural delights await your visit to the town of Wells! Stay at this well-equipped 1-bath studio and enjoy easy access to several beaches, including Wells Beach and Drakes Island Beach, as well as Rachel Carson National Wildlife Refuge - the best spot for wildlife viewing just 8 miles away. Not to mention, with the downtown area just 10 minutes from vacation rental.",
    Street: "4667 Bicetown Street",
    City: "New York",
    State: "NY",
    Country: "USA",
    ZipCode: "10004",
    guestCapacity: 1,
    Beds: 1,
    isWifiAvailable: true,
    isBreakfastAvailable: true,
    isAirConditioned: false,
    images: [
      "http://res.cloudinary.com/udemy-courses/image/upload/v1693135931/bookit/demo/ny4n2w1ubdnfktua8stg.jpg",

      "http://res.cloudinary.com/udemy-courses/image/upload/v1693135931/bookit/demo/ao7enhxobr0z1qyxgyki.jpg",
    ],
  },
  {
    name: "Picturesque 2-Story Farmhouse w/Private Hot Tub",
    price: 242,
    description:
      "Find plenty of space for a family or a large group at this picturesque Wells home, the perfect spot for a relaxing getaway in charming, quintessential Maine style! Spend your days on the beautiful nearby beaches, and come home to a large backyard and orchard where your kids can play, as well as a patio with a gas grill for barbecues on summer afternoons.",
    Street: "200 Olympic Dr",
    City: "Stafford",
    State: "VS",
    Country: "USA",
    ZipCode: "22554",
    guestCapacity: 2,
    Beds: 2,
    isWifiAvailable: true,
    isBreakfastAvailable: false,
    isAirConditioned: true,
    images: [
      "http://res.cloudinary.com/udemy-courses/image/upload/v1693136060/bookit/demo/gbabqnb7nzvc7gmmpcvg.jpg",
      "http://res.cloudinary.com/udemy-courses/image/upload/v1694680598/bookit/demo/tvheutup1idr5wi0p5bq.jpg",
    ],
  },
  {
    name: "Downtown Portsmouth Private Getaway! Hot Tub",
    price: 85,
    description:
      "Absolutely the best location in Portsmouth! Beautifully furnished, this spacious and private home is perfectly suited for taking in all of the must-see sights and historic landmarks that make this vibrant city so unique. Situated near the banks of the Piscataqua River just minutes away from Strawbery Banke Museum, Prescott Park, USS Albacore Museum, Market Square and more!",
    Street: "3747 Parkway Street",
    City: "Apple Valley",
    State: "CA",
    Country: "USA",
    ZipCode: "92307",
    guestCapacity: 3,
    Beds: 2,
    isWifiAvailable: true,
    isBreakfastAvailable: true,
    isAirConditioned: true,
    images: [
      "http://res.cloudinary.com/udemy-courses/image/upload/v1693136187/bookit/demo/nhhthdrrvaundinfnyxd.jpg",
      "http://res.cloudinary.com/udemy-courses/image/upload/v1693136187/bookit/demo/qsmprvvkshpwynqinz8i.jpg",
    ],
  },
  {
    name: "Spacious Suite in a quiet Boston neighborhood.",
    price: 95,
    description:
      "Our largest room with a queen bed and foldable sofa. Comfortably fits 2-3 adults, four adults maximum. Decorated with Irish-themed colors and arts. It has a private bathroom with a shower, equipped with smart TV, mini-fridge, desk, chairs. Enjoy City views at the sitting area by the window. Located on the 3rd floor with no elevator.",
    Street: "224 Cherry St",
    City: "Buffalo",
    State: "NY",
    Country: "USA",
    ZipCode: "14202",
    guestCapacity: 6,
    Beds: 3,
    isWifiAvailable: true,
    isBreakfastAvailable: true,
    isAirConditioned: true,
    images: [
      "http://res.cloudinary.com/udemy-courses/image/upload/v1693136394/bookit/demo/ahxbixikavvrlokgf8jp.jpg",
      "http://res.cloudinary.com/udemy-courses/image/upload/v1693136394/bookit/demo/m7hgvpqj6kbqjsma0gfy.jpg",
      "http://res.cloudinary.com/udemy-courses/image/upload/v1693136394/bookit/demo/inpn3k94tvsmdaun0dsj.jpg",
    ],
  },
  {
    name: "Shangri-La Hotel, Washington",
    price: 105,
    description:
      "Our largest room with a queen bed and foldable sofa. Comfortably fits 2-3 adults, four adults maximum. Decorated with Irish-themed colors and arts. It has a private bathroom with a shower, equipped with smart TV, mini-fridge, desk, chairs. Enjoy City views at the sitting area by the window. Located on the 3rd floor with no elevator.",
    Street: "4724  Mudlick Road",
    City: "Yakima",
    State: "WA",
    Country: "USA",
    ZipCode: "98902",
    guestCapacity: 2,
    Beds: 1,
    isWifiAvailable: true,
    isBreakfastAvailable: true,
    isAirConditioned: true,
    images: [
      "http://res.cloudinary.com/udemy-courses/image/upload/v1693136765/bookit/demo/ir1705u1vtfgzvqqdfh2.jpg",
      "http://res.cloudinary.com/udemy-courses/image/upload/v1693136765/bookit/demo/o3ieyr8gltwhwccgqzia.jpg",
    ],
  },
  {
    name: "Hotel Chimayo de Santa Fe Rooms",
    price: 36,
    description:
      "Our largest room with a queen bed and foldable sofa. Comfortably fits 2-3 adults, four adults maximum. Decorated with Irish-themed colors and arts. It has a private bathroom with a shower, equipped with smart TV, mini-fridge, desk, chairs. Enjoy City views at the sitting area by the window. Located on the 3rd floor with no elevator.",
    Street: "1029  Godfrey Street",
    City: "Portland",
    State: "OR",
    Country: "USA",
    ZipCode: "97205",
    guestCapacity: 2,
    Beds: 2,
    isWifiAvailable: true,
    isBreakfastAvailable: true,
    isAirConditioned: true,
    images: [
      "http://res.cloudinary.com/udemy-courses/image/upload/v1693136789/bookit/demo/hmvqt42lzdjc197ynrtk.jpg",
    ],
  },
  {
    name: "Hotel Garni Ischgl 4 star room comfort",
    price: 82,
    description:
      "Our largest room with a queen bed and foldable sofa. Comfortably fits 2-3 adults, four adults maximum. Decorated with Irish-themed colors and arts. It has a private bathroom with a shower, equipped with smart TV, mini-fridge, desk, chairs. Enjoy City views at the sitting area by the window. Located on the 3rd floor with no elevator.",
    Street: "2645  Parrish Avenue",
    City: "SAINT LOUIS",
    State: "MO",
    Country: "USA",
    ZipCode: "63116",
    guestCapacity: 5,
    Beds: 3,
    isWifiAvailable: true,
    isBreakfastAvailable: true,
    isAirConditioned: true,
    images: [
      "http://res.cloudinary.com/udemy-courses/image/upload/v1693136804/bookit/demo/aenyd4econmkcvyiyjkc.jpg",
    ],
  },
  {
    name: "The Spa at Base Camp at Kerry Hotel",
    price: 76,
    description:
      "Our largest room with a queen bed and foldable sofa. Comfortably fits 2-3 adults, four adults maximum. Decorated with Irish-themed colors and arts. It has a private bathroom with a shower, equipped with smart TV, mini-fridge, desk, chairs. Enjoy City views at the sitting area by the window. Located on the 3rd floor with no elevator.",
    Street: "3118  Red Hawk Road",
    City: "Garfield",
    State: "MN",
    Country: "USA",
    ZipCode: "56332",
    guestCapacity: 2,
    Beds: 1,
    isWifiAvailable: true,
    isBreakfastAvailable: false,
    isAirConditioned: true,
    images: [
      "http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg",
      "http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg",
    ],
  },
];
